import os

CORPUS_DATA = {
    "research_qc_01.txt": """Quantum computing fundamentally exploits superposition and entanglement of qubits to achieve computational speedups over classical binary architectures. Unlike classical bits restricted to 0 or 1, qubits exist in coherent superpositions, enabling massively parallel quantum gate operations. Quantum circuits built from Hadamard gates, CNOT gates, and Toffoli gates manipulate qubit registers to implement algorithms like Grover's search and quantum phase estimation. The computational advantage arises from quantum interference patterns that amplify correct solution amplitudes while destructively cancelling incorrect paths. Entanglement between qubit pairs creates non-local correlations described by Bell states, enabling quantum teleportation and superdense coding protocols. Current noisy intermediate-scale quantum (NISQ) processors from IBM, Google, and IonQ operate with 50-1000 physical qubits, though quantum error correction requires thousands of physical qubits per logical qubit. The surface code and color code are leading error correction schemes that use topological properties to protect quantum information from decoherence. Quantum volume and circuit depth metrics benchmark processor performance beyond raw qubit counts. Variational quantum eigensolvers (VQE) and quantum approximate optimization algorithms (QAOA) represent hybrid classical-quantum approaches suited for near-term hardware constraints.""",

    "research_qc_02.txt": """Quantum decoherence remains the dominant obstacle to fault-tolerant quantum computation, causing qubits to lose quantum coherence through interactions with thermal phonons and electromagnetic fluctuations in the processor environment. T1 relaxation time measures energy decay from excited to ground state, while T2 dephasing time quantifies the loss of phase coherence between superposition components. Superconducting transmon qubits achieve T1 times of 100-300 microseconds at millikelvin temperatures maintained by dilution refrigerators operating near 15 millikelvin. Trapped-ion architectures using ytterbium-171 and calcium-43 ions demonstrate coherence times exceeding several seconds, offering superior qubit fidelity at the cost of slower gate speeds. Topological qubits based on Majorana fermions in semiconductor-superconductor heterostructures promise inherent protection against local noise through non-abelian braiding operations, though experimental realization remains challenging. Quantum error correction codes such as the Steane code, Shor's 9-qubit code, and the surface code encode logical qubits across multiple physical qubits, using syndrome measurements to detect and correct bit-flip and phase-flip errors without collapsing the quantum state. The threshold theorem guarantees that arbitrarily long quantum computations are possible provided the physical error rate falls below a critical threshold, typically around 1% for surface codes. Cross-resonance and Molmer-Sorensen entangling gates achieve two-qubit gate fidelities above 99.5% in state-of-the-art processors.""",

    "research_qc_03.txt": """Quantum algorithms offer provable exponential or polynomial speedups for specific computational problems intractable on classical hardware. Shor's factoring algorithm decomposes large integers into prime factors in polynomial time using quantum Fourier transforms, directly threatening RSA-2048 encryption. Grover's unstructured search algorithm provides quadratic speedup, reducing database search from O(N) to O(sqrt(N)) oracle queries. Quantum simulation of molecular Hamiltonians using Suzuki-Trotter decomposition and qubitization enables accurate prediction of electronic ground-state energies for drug discovery and catalyst design. The quantum linear systems algorithm (HHL) solves systems of linear equations exponentially faster than classical methods, with applications in machine learning and finite element analysis. Quantum walk algorithms accelerate graph traversal problems including element distinctness and triangle finding. Quantum machine learning algorithms leverage amplitude encoding to represent exponentially large feature vectors in logarithmic qubit registers, enabling quantum kernel methods and quantum support vector machines. Variational quantum circuits with parameterized rotation gates serve as quantum neural networks, optimized through classical gradient descent on expectation value landscapes. Post-quantum cryptography standardization by NIST has selected lattice-based schemes (CRYSTALS-Kyber, CRYSTALS-Dilithium) to replace vulnerable RSA and elliptic curve systems.""",

    "research_cyber_01.txt": """Zero-trust security architectures eliminate implicit trust boundaries by enforcing continuous authentication and micro-segmentation across all network layers. Every access request undergoes identity verification through multi-factor authentication combining TOTP tokens, FIDO2 hardware keys, and biometric validation regardless of the request origin. Network micro-segmentation divides the infrastructure into granular security zones using software-defined perimeters, preventing lateral movement after initial compromise. Security Information and Event Management (SIEM) platforms aggregate logs from firewalls, intrusion detection systems (IDS), and endpoint detection and response (EDR) agents to correlate threat indicators. Extended Detection and Response (XDR) solutions unify telemetry across email gateways, cloud workloads, and network traffic for comprehensive threat visibility. The MITRE ATT&CK framework maps adversary tactics, techniques, and procedures (TTPs) across the kill chain from initial reconnaissance through privilege escalation to data exfiltration. Security orchestration and automated response (SOAR) playbooks automate incident triage, containment, and remediation workflows to reduce mean time to respond (MTTR). Privileged access management (PAM) systems enforce just-in-time elevation, session recording, and credential vaulting to minimize the blast radius of compromised administrator accounts. Deception technology deploys honeypots and honeytokens throughout production environments to detect adversaries who bypass perimeter defenses.""",

    "research_cyber_02.txt": """Ransomware operations have evolved into sophisticated double-extortion campaigns where threat actors exfiltrate sensitive data before encrypting victim systems, threatening public disclosure to compel payment. Initial access vectors typically exploit unpatched CVEs in internet-facing appliances such as VPN concentrators, Microsoft Exchange servers, and Citrix ADC gateways. Phishing campaigns delivering weaponized Office macros, ISO disk images, and OneNote attachments establish persistence through scheduled tasks, WMI event subscriptions, and registry run keys. Post-exploitation frameworks including Cobalt Strike beacons, Sliver implants, and Brute Ratel C4 enable command-and-control communications over encrypted HTTPS channels with domain fronting and malleable C2 profiles. Lateral movement leverages credential dumping via Mimikatz, pass-the-hash attacks against NTLM authentication, and Kerberoasting of service principal names to escalate domain privileges. Ransomware payloads employ AES-256 symmetric encryption with RSA-4096 wrapped keys, making decryption without the private key computationally infeasible. Ransomware-as-a-Service (RaaS) ecosystems like LockBit, BlackCat/ALPHV, and Royal operate affiliate programs with revenue-sharing models, lowering the barrier to entry for cybercriminals. Indicators of compromise (IOCs) including file hashes, mutex names, and command-and-control IP addresses are shared through STIX/TAXII threat intelligence feeds. Organizations deploy immutable backup strategies with air-gapped storage and WORM compliance to ensure recovery without ransom payment.""",

    "research_cyber_03.txt": """Vulnerability management programs systematically identify, prioritize, and remediate security flaws across enterprise attack surfaces encompassing cloud workloads, container registries, and on-premises infrastructure. Automated vulnerability scanners like Nessus, Qualys, and Rapid7 InsightVM perform authenticated credential scans to discover missing patches, misconfigurations, and compliance violations against CIS Benchmarks and DISA STIGs. The Common Vulnerability Scoring System (CVSS) assigns severity ratings from 0.0 to 10.0 based on exploitability metrics including attack vector, attack complexity, and privileges required. The Exploit Prediction Scoring System (EPSS) provides probability-based prioritization by modeling the likelihood of exploitation in the wild within the next 30 days. Software composition analysis (SCA) tools audit open-source dependencies in application manifests (package.json, requirements.txt, pom.xml) against the National Vulnerability Database (NVD) and GitHub Advisory Database. Static application security testing (SAST) analyzers detect injection flaws, buffer overflows, and insecure deserialization patterns in source code during the CI/CD pipeline. Dynamic application security testing (DAST) crawlers probe running applications for OWASP Top 10 vulnerabilities including SQL injection, cross-site scripting (XSS), and server-side request forgery (SSRF). Web application firewalls (WAFs) enforce virtual patching rules to block exploitation attempts while development teams implement permanent fixes. Bug bounty programs incentivize responsible disclosure from external security researchers through platforms like HackerOne and Bugcrowd.""",

    "research_telemed_01.txt": """Telemedicine platforms deliver synchronous and asynchronous clinical consultations through HIPAA-compliant video conferencing, secure patient messaging portals, and store-and-forward diagnostic workflows. Real-time teleconsultations connect patients with physicians via encrypted WebRTC video streams, enabling visual assessment, medication management, and behavioral health therapy sessions without in-person visits. Asynchronous teledermatology allows patients to submit clinical photographs through mobile applications for dermatologist review within 24-48 hours, significantly reducing wait times for specialist referral. Remote patient monitoring (RPM) programs continuously collect vital signs including blood pressure, pulse oximetry, blood glucose, and weight through Bluetooth-enabled medical devices that transmit readings to cloud-based electronic health record (EHR) systems. Chronic care management protocols for diabetes, hypertension, congestive heart failure, and COPD use RPM data to trigger automated clinical alerts when physiological parameters exceed individualized thresholds. The Centers for Medicare and Medicaid Services (CMS) reimburse telehealth encounters under CPT codes 99201-99215 for evaluation and management services, with RPM services billed under CPT 99453, 99454, and 99457. Telehealth adoption accelerated dramatically during the COVID-19 pandemic, with virtual visit volumes increasing over 3000% compared to pre-pandemic baselines. Integration with pharmacy networks enables electronic prescribing (e-prescribing) of medications including Schedule II-V controlled substances through state-approved telehealth prescribing frameworks.""",

    "research_telemed_02.txt": """Wearable biosensors integrated with telehealth infrastructure enable continuous physiological monitoring outside traditional clinical settings, transforming chronic disease management from episodic to proactive care delivery. Photoplethysmography (PPG) sensors in smartwatches detect irregular heart rhythms including atrial fibrillation with sensitivity exceeding 94%, prompting cardiologist teleconsultation for confirmatory electrocardiogram interpretation. Continuous glucose monitors (CGMs) such as Dexcom G7 and Abbott FreeStyle Libre transmit interstitial glucose readings every 5 minutes to smartphone applications, allowing endocrinologists to remotely adjust insulin dosing through telehealth portals. Implantable cardiac monitors like the Medtronic LINQ transmit arrhythmia episodes and heart failure hemodynamic data through cellular gateways to remote monitoring centers staffed by cardiac device nurses. Pulmonary rehabilitation programs deploy home spirometry devices that measure forced expiratory volume (FEV1) and peak expiratory flow (PEF), with readings reviewed by pulmonologists during scheduled telehealth appointments. Mental health platforms utilize ecological momentary assessment (EMA) through smartphone-delivered questionnaires (PHQ-9, GAD-7) to track depression and anxiety symptom trajectories between telepsychiatry sessions. Data interoperability between wearable platforms and EHR systems relies on HL7 FHIR (Fast Healthcare Interoperability Resources) APIs to standardize clinical data exchange. Patient-generated health data (PGHD) governance frameworks address consent, data ownership, and secondary research use under HIPAA Privacy Rule provisions.""",

    "research_telemed_03.txt": """Healthcare policy frameworks governing telemedicine practice must address interstate medical licensure, prescribing authority, malpractice liability, and reimbursement parity to enable sustainable virtual care delivery at scale. The Interstate Medical Licensure Compact allows physicians to obtain expedited licenses in participating member states, reducing administrative barriers to cross-border teleconsultation. The Ryan Haight Online Pharmacy Consumer Protection Act requires at least one in-person evaluation before prescribing controlled substances via telemedicine, though DEA pandemic-era flexibilities temporarily waived this requirement. Malpractice insurance carriers have developed telemedicine-specific endorsements addressing jurisdictional liability questions when physicians treat patients across state boundaries. The Federal Communications Commission (FCC) Connected Care Pilot Program and USDA ReConnect Program fund broadband infrastructure deployment in underserved rural communities to eliminate connectivity barriers to telehealth access. Digital health literacy interventions using community health workers and patient navigators improve technology adoption rates among elderly and low-income populations. Mobile health (mHealth) applications must comply with FDA medical device regulations when they transform smartphone sensors into diagnostic instruments, requiring 510(k) premarket clearance for Class II devices. Telestroke networks connect rural emergency departments with board-certified vascular neurologists through high-definition video consultation, enabling administration of tissue plasminogen activator (tPA) within the critical 4.5-hour treatment window. Health equity metrics track telemedicine utilization rates stratified by race, age, income, and geography to identify and address disparities in virtual care access."""
}

def generate_text_corpus(target_folder="research_documents"):
    os.makedirs(target_folder, exist_ok=True)

    for doc_title, text_body in CORPUS_DATA.items():
        file_path = os.path.join(target_folder, doc_title)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(text_body)

    print(f"Dataset successfully created in '{target_folder}' with {len(CORPUS_DATA)} text files.")

if __name__ == "__main__":
    generate_text_corpus()